image: Visual Studio 2017

clone_depth: 5

environment:
  Path: '%Path%;C:\texlive\bin\win32'
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: '-t7z -mx1'

install:
  - ps: cd .\.ci; .\install.ps1

build_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER && ./build.sh all"

after_build:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER && .ci/pack.sh"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: '*.pdf'
  - path: 'nuaathesis.tar.gz'
  - path: 'nuaathesis.zip'

cache:
  - C:\texlive
